---
title: "Between-within Degree of Freedom"
package: mmrm
bibliography: '`r system.file("REFERENCES.bib", package = "mmrm")`'
output:
  rmarkdown::html_document:
          theme: "spacelab"
          highlight: "kate"
          toc: true
          toc_float: true
vignette: |
  %\VignetteIndexEntry{Between-within Degree of Freedom}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
  markdown:
    wrap: 72
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Here we describe the "Between-within" degree of freedom.

# Introduction

Between-within degree of freedom is calculate by deviding the degree of freedom of residuals,
into between-subject degree of freedom and within-subject degree of freedom.

# Details

According to @schluchter1990small, and following the notation in [details of model fitting](algorithm.html#model-definition), we have

\[
  \nu_{between} = n - dim(\beta)
\]

\[
  \nu_{within} = \sum_{i}{m_i}- n - dim(\beta)
\]

where $dim(\beta)$ is the number of parameters, $n$ is the number of subjects, $m_i$ is the number of visits for subject $i$.

# Choosing the Degree of Freedom

Now we have between-subject degree of freedom and within-subject degree of freedom.
Which degree of freedom to choose is dependent on which element of $beta$ need to be tested.
If the corresponding variable changes for any of the subjects, within-subject degree of freedom is used.
If the corresponding variable does not change for all subjects, between-subject degree of freedom is used.

For example, in `fev_data`, we have `AVISIT`, `ARMCD`, etc.
If the model is `FEV1 ~ AVISIT + ARMCD + ar1(AVISIT|USUBJID)`.
If we are going to test whether the coefficient of `ARMCD` (TRT vs PBO), then between-subject degree of freedom is used,
as `ARMCD` are the same within each subject.
However, if the coefficient of `AVISIT`(VIS4 vs VIS1, VIS3 vs VIS1 and VIS2 vs VIS1), within-subject degree of freedom is used,
as `AVISIT` changes for each subject.
