---
title: "Implementations of MMRM: a comparison of what's available"
package: mmrm
bibliography: mmrm_review_refs.bib
output:
  rmarkdown::html_document:
          theme: "spacelab"
          highlight: "kate"
          toc: true
          toc_float: true
          toc_depth: 2
vignette: |
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{Implementations of MMRM: a comparison of what's available}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
  markdown:
    wrap: 72
---

# Introduction

In this vignette we briefly compare the `mmrm::mmrm`, `SAS PROC MIXED`,
`nlme::gls`, `lme4::lmer`, and `glmmTMB::glmmTMB` methods' capabilities. A
primary difference lies in what is supported in terms of covariance structures.
In particular, `SAS PROC MIXED` and `mmrm` are the only implementations which
provide support for many of the most common covariance structures. `gls`, `lmer`
and `glmmTMB` are more limited. `mmmrm` also generally converges more quickly
than other procedures regardless of the specified covariance structure.

# Dataset

The FEV data set is contains measurements of FEV1 (forced expired volume in one
second), a measure of how quickly the lungs can be emptied. Low levels of FEV1
may indicate chronic obstructive pulmonary disease (COPD). This data set is used
to illustrate model fitting with the `mmrm`, `lme4`, `nlme`, `glmmTMB` R
packages as well as `SAS`. It is summarized below.

```
                                      Stratified by ARMCD
                               Overall       PBO           TRT           
  n                              800           420           380        
  USUBJID 
     PT[1-200]                   800           420           380  
  AVISIT (%)                                                             
     VIS1                        200 (25.0)    105 (25.0)     95 ( 25.0) 
     VIS2                        200 (25.0)    105 (25.0)     95 ( 25.0) 
     VIS3                        200 (25.0)    105 (25.0)     95 ( 25.0) 
     VIS4                        200 (25.0)    105 (25.0)     95 ( 25.0) 
  ARMCD = TRT (%)                380 (47.5)      0 ( 0.0)    380 (100.0) 
  RACE (%)                                                               
     Asian                       280 (35.0)    152 (36.2)    128 ( 33.7) 
     Black or African American   300 (37.5)    184 (43.8)    116 ( 30.5) 
     White                       220 (27.5)     84 (20.0)    136 ( 35.8) 
  SEX = Female (%)               424 (53.0)    220 (52.4)    204 ( 53.7) 
  FEV1_BL (mean (SD))          40.19 (9.12)  40.46 (8.84)  39.90 (9.42)  
  FEV1 (mean (SD))             42.30 (9.32)  40.24 (8.67)  44.45 (9.51)  
  WEIGHT (mean (SD))            0.52 (0.23)   0.52 (0.23)   0.51 (0.23)  
  VISITN (mean (SD))            2.50 (1.12)   2.50 (1.12)   2.50 (1.12)  
  VISITN2 (mean (SD))          -0.02 (1.03)   0.01 (1.07)  -0.04 (0.98)  
```

# Model Implementations {.tabset}

Listed below are some of the most commonly used covariance structures used when
fitting mixed models for repeated measures. We emphasize that this table is not
exhaustive; `SAS PROC MIXED` and `glmmTMB` support additional spatial covariance
structures.

| Covariance structures             | mmrm | PROC MIXED | gls | lmer | glmmTMB |
|:---------------------------------:|:----:|:----------:|:---:|:----:|:-------:|
| Ante-dependence (heterogeneous)   | X    | X          |     |      |         |
| Ante-dependence (homogeneous)     | X    |            |     |      |         |
| Auto-regressive (heterogeneous)   | X    | X          | X   |      |         |
| Auto-regressive (homogeneous)     | X    | X          |     |      | X       |
| Ante-dependence (homogeneous)     | X    |            |     |      |         |
| Compound symmetry (heterogeneous) | X    | X          | X   |      | X       |
| Compound symmetry (homogeneous)   | X    | X          |     |      |         |
| Spatial exponential               | X    | X          | X   |      | X       |
| Toeplitz (heterogeneous)          | X    | X          |     |      | X       |
| Toeplitz (homogeneous)            | X    | X          |     |      |         |
| Unstructured                      | X    | X          | X   | X    | X       |

**NOTE: Should we mention other covariance matrix structures not implemented in
`mmrm`?**

Code for fitting mixed models for repeated measures using each of the considered
functions and covariance structures are provided below.

## Ante-dependence (heterogeneous)

### PROC MIXED
<pre><code>PROC MIXED DATA = fev_data cl method=ml;
CLASS AVISIT(ref = 'VIS4') USUBJID;
MODEL FEV1 = / ddfm=satterthwaite solution chisq;
<b>REPEATED AVISIT / subject=USUBJID type=ANTE(1)</b> r=1, 2, 3, 4, 5, 6, 7, 8, 9, 10 rcorr;
</code></pre>

### mmrm
<pre><code>mmrm(formula = FEV1 ~ <b>adh(VISITN | USUBJID)</b>, data = fev_data)
</code></pre>

## Ante-dependence (homogeneous)

### mmrm
<pre><code>mmrm(formula = FEV1 ~ <b>ad(VISITN | USUBJID)</b>, data = fev_data)
</code></pre>

## Auto-regressive (heterogeneous)

### PROC MIXED
<pre><code>PROC MIXED DATA = fev_data cl method=ml;
CLASS AVISIT(ref = 'VIS4') USUBJID;
MODEL FEV1 = / ddfm=satterthwaite solution chisq;
<b>REPEATED AVISIT / subject=USUBJID type=ARH(1)</b> r=1, 2, 3, 4, 5, 6, 7, 8, 9, 10 rcorr;
</code></pre>

### mmrm
<pre><code>mmrm(formula = FEV1 ~ <b>ar1h(VISITN | USUBJID)</b>, data = fev_data)
</code></pre>

### gls
<pre><code>gls(
  formula = FEV1 ~  SEX + ARMCD * AVISIT,
  data = fev_data,
  correlation = <b>corCAR1(form = ~AVISIT | USUBJID)</b>,
  weights = varIdent(form = ~1|AVISIT),
  na.action = na.omit
)
</code></pre>

## Auto-regressive (homogeneous)

### PROC MIXED
<pre><code>PROC MIXED DATA = fev_data cl method=ml;
CLASS AVISIT(ref = 'VIS4') USUBJID;
MODEL FEV1 = / ddfm=satterthwaite solution chisq;
<b>REPEATED AVISIT / subject=USUBJID type=AR(1)</b> r=1, 2, 3, 4, 5, 6, 7, 8, 9, 10 rcorr;
</code></pre>

### mmrm
<pre><code>mmrm(formula = FEV1 ~ <b>ar1(VISITN | USUBJID)</b>, data = fev_data)
</code></pre>

### glmmTMB
<pre><code>glmmTMB(
  FEV1 ~ ARMCD * AVISIT + RACE + SEX + <b>ar1(0 + AVISIT | USUBJID)</b>,
  <b>dispformula = ~ 0</b>,
  data = fev_data
)
</code></pre>

## Compound symmetry (heterogeneous)

### PROC MIXED
<pre><code>PROC MIXED DATA = fev_data cl method=ml;
CLASS AVISIT(ref = 'VIS4') USUBJID;
MODEL FEV1 = / ddfm=satterthwaite solution chisq;
<b>REPEATED AVISIT / subject=USUBJID type=CSH</b> r=1, 2, 3, 4, 5, 6, 7, 8, 9, 10 rcorr;
</code></pre>

### mmrm
<pre><code>mmrm(formula = FEV1 ~ <b>csh(VISITN | USUBJID)</b>, data = fev_data)
</code></pre>

### gls
<pre><code>gls(
  formula = FEV1 ~  SEX + ARMCD * AVISIT,
  data = fev_data,
  correlation = <b>corCompSymm(form = ~AVISIT | USUBJID)</b>,
  weights = varIdent(form = ~1|AVISIT),
  na.action = na.omit
)
</code></pre>

### glmmTMB
<pre><code>glmmTMB(
  FEV1 ~ ARMCD * AVISIT + RACE + SEX + <b>cs(0 + AVISIT | USUBJID)</b>,
  <b>dispformula = ~ 0</b>,
  data = fev_data
)
</code></pre>

## Compound symmetry (homogeneous)

### PROC MIXED
<pre><code>PROC MIXED DATA = fev_data cl method=ml;
CLASS AVISIT(ref = 'VIS4') USUBJID;
MODEL FEV1 = / ddfm=satterthwaite solution chisq;
<b>REPEATED AVISIT / subject=USUBJID type=CS</b> r=1, 2, 3, 4, 5, 6, 7, 8, 9, 10 rcorr;
</code></pre>

### mmrm
<pre><code>mmrm(formula = FEV1 ~ <b>cs(VISITN | USUBJID)</b>, data = fev_data)
</code></pre>

## Spatial exponential

### PROC MIXED 
<pre><code>PROC MIXED DATA = fev_data cl method=ml;
CLASS USUBJID;
MODEL FEV1 = / ddfm=satterthwaite solution chisq;
<b>REPEATED / subject=USUBJID type=sp(exp)(visitn)</b> rcorr;
</code></pre>

### mmrm
<pre><code>mmrm(formula = FEV1 ~ <b>sp_exp(VISITN | USUBJID)</b>, data = fev_data)
</code></pre>

### gls
<pre><code>gls(
  formula = FEV1 ~  SEX + ARMCD * AVISIT,
  data = fev_data,
  correlation = <b>corExp(form = ~AVISIT | USUBJID)</b>,
  weights = varIdent(form = ~1|AVISIT),
  na.action = na.omit
)
</code></pre>

### glmmTMB
<pre><code># NOTE: requires use of coordinates
glmmTMB(
  FEV1 ~ ARMCD * AVISIT + RACE + SEX + <b>exp(0 + AVISIT | USUBJID)</b>,
  <b>dispformula = ~ 0</b>,
  data = fev_data
)
</code></pre>

## Toeplitz (heterogeneous)

### PROC MIXED
<pre><code>PROC MIXED DATA = fev_data cl method=ml;
CLASS AVISIT(ref = 'VIS4') USUBJID;
MODEL FEV1 = / ddfm=satterthwaite solution chisq;
<b>REPEATED AVISIT / subject=USUBJID type=TOEPH</b> r=1, 2, 3, 4, 5, 6, 7, 8, 9, 10 rcorr;
</code></pre>

### mmrm
<pre><code>mmrm(formula = FEV1 ~ <b>toeph(AVISIT | USUBJID)</b>, data = fev_data)
</code></pre>

### glmmTMB
<pre><code> glmmTMB(
  FEV1 ~ ARMCD * AVISIT + RACE + SEX + <b>toep(0 + AVISIT | USUBJID)</b>,
  <b>dispformula = ~ 0</b>,
  data = fev_data
)
</code></pre>

## Toeplitz (homogeneous)

### PROC MIXED
<pre><code>PROC MIXED DATA = fev_data cl method=ml;
CLASS AVISIT(ref = 'VIS4') USUBJID;
MODEL FEV1 = / ddfm=satterthwaite solution chisq;
<b>REPEATED AVISIT / subject=USUBJID</b> <b>type=TOEP</b> r=1, 2, 3, 4, 5, 6, 7, 8, 9, 10 rcorr;
</code></pre>

### mmrm
<pre><code>mmrm(formula = FEV1 ~ <b>toep(AVISIT | USUBJID)</b>, data = fev_data)
</code></pre>

## Unstructured

### PROC MIXED
<pre><code>PROC MIXED DATA = fev_data cl method=reml;
CLASS AVISIT(ref = 'VIS1') SEX(ref = 'Male') ARMCD(ref = 'PBO') USUBJID;
MODEL FEV1 = ARMCD AVISIT ARMCD*AVISIT SEX / ddfm=satterthwaite solution chisq;
<b>REPEATED AVISIT / subject=USUBJID type=un</b> r rcorr;
</code></pre>
  
### mmrm
<pre><code>mmrm(formula = FEV1 ~ SEX + ARMCD * AVISIT + <b>us(AVISIT | USUBJID)</b>, data = fev_data)
</code></pre>
  
### gls
<pre><code>gls(
  formula = FEV1 ~  SEX + ARMCD * AVISIT,
  data = fev_data,
  correlation = <b>corSymm(form = ~AVISIT | USUBJID)</b>,
  weights = varIdent(form = ~1|AVISIT),
  na.action = na.omit
)
</code></pre>

### lmer
<pre><code>lmer(
  FEV1 ~ SEX + ARMCD * AVISIT + <b>(0 + AVISIT | USUBJID)</b>,
  data = fev_data,
  control = lmerControl(check.nobs.vs.nRE = "ignore"),
  na.action = na.omit
)
</code></pre>

### glmmTMB
<pre><code>glmmTMB(
  FEV1 ~ ARMCD * AVISIT + RACE + SEX + <b>us(0 + AVISIT | USUBJID)</b>,
  <b>dispformula = ~ 0</b>,
  data = fev_data
)
</code></pre>


# Benchmarking

Next, the mixed models for repeated measures procedures are compared. Their
convergence times are evaluated first, followed by a comparison of their
estimates.

## Convergence Times

```{r, warning=FALSE, message=FALSE, include=FALSE, echo=FALSE, eval=FALSE}
library(microbenchmark)
library(dplyr)
library(mmrm)
library(lme4)
library(nlme)
library(glmmTMB)
library(sasr)

# set the number of replicates
n_reps <- 10

# assess convergence times for R-based MMRM procedures
mb <- microbenchmark(times = n_reps,
  gls = gls(
    FEV1 ~ RACE + ARMCD * AVISIT, data = fev_data,
    na.action = na.omit,
    correlation = nlme::corSymm(form = ~ VISITN | USUBJID),
    weights = nlme::varIdent(form = ~ 1|VISITN)
  ),
  mmrm = mmrm(
    formula = FEV1 ~ RACE + ARMCD * AVISIT + us(AVISIT | USUBJID),
    data = fev_data
  ),
  lmer = lmer(
    FEV1 ~ RACE + ARMCD * AVISIT + (0 + AVISIT | USUBJID),
    data = fev_data,
    control = lmerControl(check.nobs.vs.nRE = "ignore"),
    na.action = na.omit
  ),
  glmmTMB = glmmTMB(
    FEV1 ~ RACE + ARMCD * AVISIT + us(0 + AVISIT | USUBJID),
    data = fev_data,
    dispformula = ~ 0,
    REML = TRUE
  )
 )

# construct the partial results table based on R-based MMRM procedures
partial_conv_time_tbl <- mb %>%
  summary() %>%
  arrange(median) %>%
  select(expression = expr, median, lower = lq, upper = uq, evaluations = neval)

# fit PROC MIXED 10 times, extract convergence times
fit_times <- sapply(
  seq_len(n_reps),
  function(x) {
    # load the data into SAS
    df2sd(fev_data, "sas_df")

    sas_code <- "
      PROC MIXED DATA = fev_data cl method=reml;
        CLASS AVISIT(ref = 'VIS1') SEX(ref = 'Male') ARMCD(ref = 'PBO') USUBJID;
        MODEL FEV1 = ARMCD AVISIT ARMCD*AVISIT SEX / ddfm=satterthwaite solution chisq;
        REPEATED AVISIT / subject=USUBJID type=un r rcorr;
     RUN;
    "

    # generate the SAS output
    sas_result <- sasr::run_sas(sas_code)

    # extract the fit time
    fit_time <- sas_result$LOG %>%
      stringr::str_extract("(?<=user cpu time)\\s*[0-9.]+") %>%
      as.numeric()
  }
)

# add PROC MIXED results to convergence results table
proc_mixed_row <- tibble(
  expression = "PROC MIXED",
  median = median(fit_time),
  lower = quantile(fit_time, probs = 0.25),
  upper = quantile(fit_time, probs = 0.75),
  evaluations = n_reps
)
conv_time_tbl <- bind_rows(partial_conv_time_tbl, proc_mixed_row)

# format the table in markdown
conv_time_tbl %>%
  knitr::kable(caption = "Comparison of convergence times: milliseconds", digits = 2)
```

The `mmrm`, `PROC MIXED`, `gls`, `lmer`, and `glmmTMB` functions, all using
unstructured covariance matrices, are applied to the FEV data 10 times. The
convergence times are recorded for each replicate and are reported in the table
below.

Table: Comparison of convergence times: milliseconds

| expression | median |  lower |  upper | evaluations |
|:-----------|-------:|-------:|-------:|------------:|
| mmrm       |  34.05 |  33.39 |  34.22 |          10 |
| PROC MIXED |      ? |      ? |      ? |           ? |
| lmer       |  70.33 |  68.13 |  70.81 |          10 |
| gls        | 226.98 | 211.81 | 232.41 |          10 |
| glmmTMB    | 321.83 | 300.88 | 343.68 |          10 |

It is clear from these results that `mmrm` converges significantly faster than
other functions. Though not demonstrated here, this is generally true regardless
of the sample size and covariance structure used.

**NOTE: Still need to generate PROC MIXED results using `sasr`**
