miss: ['no', 'low', 'high', 'extreme']
trt: ['no', 'small', 'mod']
cov: ['us', 'toeph', 'csh']
n: ['200', '400', '600']
seed: ['13412112']
reml: ['reml', 'ml']
covar_rsp: ['us', 'toeph', 'csh']
rep: 1000
