# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test2 <- function(x, subject_zero_inds, visits_zero_inds, n_subjects, subject_n_visits, n_visits, cov_type, is_spatial, theta) {
    .Call(`_mmrm_test2`, x, subject_zero_inds, visits_zero_inds, n_subjects, subject_n_visits, n_visits, cov_type, is_spatial, theta)
}

