---
name: Check 🛠

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  audit:
    name: Audit Dependencies 🕵️‍♂️
    uses: insightsengineering/r.pkg.template/.github/workflows/audit.yaml@main
  r-cmd:
    name: R CMD Check 🧬
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      additional-r-cmd-check-params: --as-cran
      unit-test-report-brand: >-
        https://raw.githubusercontent.com/insightsengineering/hex-stickers/main/thumbs/mmrm.png
  coverage:
    name: Coverage 📔
    uses: insightsengineering/r.pkg.template/.github/workflows/test-coverage.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  linter:
    if: github.event_name == 'pull_request'
    name: SuperLinter 🦸‍♀️
    uses: insightsengineering/r.pkg.template/.github/workflows/linter.yaml@main
  roxygen:
    name: Roxygen 🅾
    uses: insightsengineering/r.pkg.template/.github/workflows/roxygen.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      auto-update: true
  gitleaks:
    name: gitleaks 💧
    uses: insightsengineering/r.pkg.template/.github/workflows/gitleaks.yaml@main
  spelling:
    if: github.event_name == 'pull_request'
    name: Spell Check 🆎
    uses: insightsengineering/r.pkg.template/.github/workflows/spelling.yaml@main
  vbump:
    name: Version Bump 🤜🤛
    if: github.event_name == 'push'
    uses: insightsengineering/r.pkg.template/.github/workflows/version-bump.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  version:
    name: Version Check 🏁
    uses: insightsengineering/r.pkg.template/.github/workflows/version.yaml@main
  licenses:
    name: License Check 🃏
    uses: insightsengineering/r.pkg.template/.github/workflows/licenses.yaml@main
